#!/usr/bin/env python3
"""Rebuild navigation from catalog/queues. No network, no edits to research cards or logs."""
from pathlib import Path
import json,re,unicodedata
ROOT=Path(__file__).resolve().parents[1]
def read(name):return json.loads((ROOT/'data'/name).read_text())
def write(path,text): (ROOT/path).write_text(text.rstrip()+'\n')
def norm(s):return ''.join(c for c in unicodedata.normalize('NFKC',s).casefold() if c.isalnum())
cat=read('catalog.json');base=read('baseline.json');cand=read('candidates.json');refs=read('reference-frontier.json');topics=read('navigation.json');awesome=read('awesome.json')
seen_ids=set();seen_titles=set()
for x in cat:
 aid=re.sub(r'v\d+$','',x.get('arxiv_id',''));title=norm(x['title'])
 assert not aid or aid not in seen_ids, f'Duplicate arXiv ID: {aid}'
 assert title not in seen_titles, f'Duplicate title: {title}'
 seen_ids.add(aid);seen_titles.add(title);assert (ROOT/x['note']).exists(),x['note']
for x in cand:
 assert re.sub(r'v\d+$','',x.get('arxiv_id','')) not in seen_ids, f'Candidate already has card: {x["title"]}'
by_slug={Path(x['note']).stem:x for x in cat}
nav='[首页](README.md) · [主题](topics.md) · [证据对照](evidence-map.md) · [综述提纲](survey-outline.md) · [论文总索引](papers/README.md)'
generated='<!-- Generated by scripts/build_index.py; edit data sources, not this index. -->\n'
# One primary place per reviewed card. This overview is a navigation table, not a ranking.
listed=[]
for group in awesome:
 assert group['key'] and group['title'] and group['question']
 for item in group['papers']:
  slug=item['slug'];summary=item['summary'].strip()
  assert slug in by_slug,f'Unknown overview slug: {slug}'
  assert 12<=len(summary)<=100 and '|' not in summary and '\n' not in summary,f'Invalid overview summary: {slug}'
  listed.append(slug)
assert len(listed)==len(set(listed)), 'Duplicate overview card'
assert set(listed)==set(by_slug), f'Overview coverage mismatch: {set(by_slug)-set(listed)} / {set(listed)-set(by_slug)}'
s=generated+'[写作工作台](../README.md) · [主题导航](../topics.md) · [证据对照](../evidence-map.md) · [综述提纲](../survey-outline.md)\n\n# 论文速览 · Awesome Physical AI RSI\n\n'
s+=f'**{len(cat)} 篇正式阅读卡片**，按研究问题分组；组内为建议阅读顺序，**不是性能或可信度排名**。点击短名看完整题名、核心图、实验口径及局限；点击 arXiv ID 回原文。作者结果未独立复现。\n\n'
s+=f'[原报告 {len(base)} 项（待逐项复核）](../baseline.md) · [摘要候选 {len(cand)} 项](../candidates.md) · [BibTeX](../references.bib)\n\n'
s+=' · '.join(f"[{group['title']}](#{group['key']})" for group in awesome)+'\n\n'
for group in awesome:
 s+=f"<a id=\"{group['key']}\"></a>\n\n## {group['title']} · {len(group['papers'])} 篇\n\n> {group['question']}\n\n"
 s+='| 工作（阅读卡片） | 一句话：做了什么 | 综述定位 | 原文 |\n| :--- | :--- | :--- | :--- |\n'
 for item in group['papers']:
  x=by_slug[item['slug']]
  short=x['short'].replace('|',r'\|')
  relation=x['tags'][0].replace('|',r'\|')
  source=f"{x['arxiv_id']}{x.get('version','')}"
  s+=f"| [{short}]({Path(x['note']).name}) | {item['summary']} | {relation} | [arXiv:{source}]({x['url']}) |\n"
 s+='\n'
s+='## 如何使用这张表\n\n- “综述定位”沿用卡片标签：**核心机制、边界案例、支撑组件、评价框架、综述**等不在同一性能尺度。尤其“严格递归候选”仍需检查外层更新与独立验收。\n- 表格仅作快速定位；写论文时打开卡片核对任务、平台、分母、人工预算、原图与证据边界，再从卡片回到原文。\n- 新论文先核查全文再加入正式卡片；只读摘要的工作留在[候选队列](../candidates.md)。\n'
write('papers/README.md',s)
s=generated+nav+'\n\n# 按研究问题找论文\n\n同一论文可以进入多个主题。主题是检索入口，不是证据等级；“改进器”主题也不代表已经证明严格递归。\n\n'
s+=' · '.join(f"[{t['title']}](#{t['key']})" for t in topics)+'\n\n'
for t in topics:
 s+=f"<a id=\"{t['key']}\"></a>\n\n## {t['title']}\n\n> {t['question']}\n\n"
 for slug in t['slugs']:
  x=by_slug[slug];s+=f"- [{x['title']}]({x['note']}) — {' / '.join(x['tags'])}\n"
 s+='\n'
s+='## 原报告主线也要回看\n\n[141 项原报告索引](baseline.md)包含 RISE、Motus2、LWD、π*0.6 / RECAP、RoboCat、Eureka、DrEureka、POET、Voyager 等。它们没有因为此次重排而被删除；这里的“原报告已有”不表示已按新版卡片逐项复核。先确认原始版本和实验，再纳入综述结论。\n'
write('topics.md',s)
s=generated+nav+'\n\n# 原报告条目索引\n\n'+f'保留 **{len(base)} 项**既有题名和公开来源，供检索、去重与回读。**没有在本轮重新审核原报告全部内容**；其中包含论文、观点和企业材料，不能统一当作经审稿实证。\n\n'
for x in sorted(base,key=lambda x:x['title'].casefold()):
 urls=x.get('urls',[]);url=next((u for u in urls if '/abs/' in u),urls[0] if urls else '')
 s+=f"- [{x['title']}]({url})" if url else f"- {x['title']}"
 s+=' — '+x.get('short',x['title'])+'\n'
write('baseline.md',s)
s=generated+nav+'\n\n# 候选与待核查\n\n'+f'**{len(cand)} 项**。下列条目未完成全文方法/结果核查，不计入正式卡片。优先级表示下一步阅读顺序，不能作为可信度评分。\n\n'
for priority in ['优先','次优先','暂不纳入主线']:
 items=[x for x in cand if x.get('priority')==priority]
 s+=f'## {priority} · {len(items)} 项\n\n'
 for x in sorted(items,key=lambda x:(x.get('discovered',''),x['title']),reverse=True):
  s+=f"- **[{x['title']}]({x['url']})**\n  - `{x.get('arxiv_id','')}` · 发现 {x.get('discovered','未记录')} · {x['status']}\n  - 下一步：{x['next_check']}\n\n"
other=[x for x in cand if x.get('priority') not in ['优先','次优先','暂不纳入主线']]
assert not other,f'Unrendered candidate priority: {other}'
write('candidates.md',s)
s=generated+nav+'\n\n# 引文溯源队列\n\n'+f'**{len(refs)} 条引文线索**，不是 {len(refs)} 篇已读论文。保留发现路径和原文定位；可能与原报告/候选重叠，升级前仍须按 ID、DOI、题名和作者合并。\n\n'
for x in sorted(refs,key=lambda x:x.get('discovered',''),reverse=True):
 s+=f"- **{x['reference']}**\n  - 发现于：[引用它的原文]({x['cited_by']})\n  - {x['status']}\n"
 if x.get('urls'):s+='  - 原始入口：'+' · '.join(f'[来源]({u})' for u in x['urls'])+'\n'
 s+='\n'
write('references.md',s)
# Human-readable citation keys; arXiv records, not guessed publication venues.
bib=[]
for x in sorted(cat,key=lambda x:x['title'].casefold()):
 year=x.get('citation_date',x['added'])[:4];key=Path(x['note']).stem+'-'+year
 esc=lambda t:t.replace('&',r'\&').replace('%',r'\%')
 authors=x.get('authors',[])
 if not authors:continue
 bib.append('@misc{'+key+',\n  title = {{'+esc(x['title'])+'}},\n  author = {'+' and '.join(authors)+'},\n  year = {'+year+'},\n  eprint = {'+x['arxiv_id']+'},\n  archivePrefix = {arXiv},\n  url = {'+x['url']+'},\n  note = {Reviewed version '+x.get('version','unspecified')+'; accessed '+x['updated']+'}\n}')
write('references.bib','\n\n'.join(bib))
# Only update the clearly delimited stats region on the manually curated homepage.
r=ROOT/'README.md'
if r.exists():
 s=r.read_text();stats=f'**{len(cat)} 篇阅读卡片** · **{len(base)} 项原报告条目** · **{len(cand)} 项待核查** · **{len(refs)} 条引文线索**'
 s=re.sub(r'<!-- stats:start -->.*?<!-- stats:end -->','<!-- stats:start -->\n'+stats+'\n<!-- stats:end -->',s,flags=re.S);write('README.md',s)
print(f'Generated indices: {len(cat)} cards, {len(base)} baseline, {len(cand)} candidates, {len(refs)} references; BibTeX {len(bib)}.')
